sotm/config/routes.rb
Sotm::Application.routes.draw do
  resources :biddings

  resources :auctions

  root :to => 'auctions#index'
  match ':controller(/:action(/:id))(.:format)'

end

sotm/app/models/auction.rb
class Auction < ActiveRecord::Base
end

sotm/app/models/bidding.rb
class Bidding < ActiveRecord::Base
end

sotm/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

sotm/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @auctions }
    end
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
    @auction = Auction.find(params[:id])

    @biddings = Bidding.find(:all, 
                            :conditions => 
                                ["auction_uniq_id=?",@auction.auction_uniq_id],
                            :order => "created_at DESC",
                            :limit => 10
                            )
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.json
  def new
    @auction = Auction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(params[:auction])

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render json: @auction, status: :created, location: @auction }
      else
        format.html { render action: "new" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.json
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction = Auction.find(params[:id])
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end

  # POST /auctions/bid
  # POST /auctions/bid/1
  def bid
    @bidding = Bidding.new(params[:bidding])

    respond_to do |format|
      if @bidding.save
        format.html { redirect_to "/auctions" }
      else
        format.html { redirect_to "/auctions" }
      end
    end
  end

end

sotm/app/controllers/biddings_controller.rb
class BiddingsController < ApplicationController
  # GET /biddings
  # GET /biddings.json
  def index
    @biddings = Bidding.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @biddings }
    end
  end

  # GET /biddings/1
  # GET /biddings/1.json
  def show
    @bidding = Bidding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bidding }
    end
  end

  # GET /biddings/new
  # GET /biddings/new.json
  def new
    @bidding = Bidding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bidding }
    end
  end

  # GET /biddings/1/edit
  def edit
    @bidding = Bidding.find(params[:id])
  end

  # POST /biddings
  # POST /biddings.json
  def create
    @bidding = Bidding.new(params[:bidding])

    respond_to do |format|
      if @bidding.save
        format.html { redirect_to @bidding, notice: 'Bidding was successfully created.' }
        format.json { render json: @bidding, status: :created, location: @bidding }
      else
        format.html { render action: "new" }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /biddings/1
  # PUT /biddings/1.json
  def update
    @bidding = Bidding.find(params[:id])

    respond_to do |format|
      if @bidding.update_attributes(params[:bidding])
        format.html { redirect_to @bidding, notice: 'Bidding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bidding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biddings/1
  # DELETE /biddings/1.json
  def destroy
    @bidding = Bidding.find(params[:id])
    @bidding.destroy

    respond_to do |format|
      format.html { redirect_to biddings_url }
      format.json { head :no_content }
    end
  end
end

sotm/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

sotm/app/helpers/application_helper.rb
module ApplicationHelper
end

sotm/app/helpers/auctions_helper.rb
module AuctionsHelper
end

sotm/app/helpers/biddings_helper.rb
module BiddingsHelper
end

sotm/app/helpers/pages_helper.rb
module PagesHelper
end

sotm/app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url_main %><br />
    <%= f.text_field :image_url_main %>
  </div>
  <div class="field">
    <%= f.label :image_url_sub %><br />
    <%= f.text_field :image_url_sub %>
  </div>
  <div class="field">
    <%= f.label :winner %><br />
    <%= f.text_field :winner %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :auction_uniq_id %><br />
    <%= f.text_field :auction_uniq_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sotm/app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

sotm/app/views/auctions/index.html.erb
<script language="javascript">
function jump(id){
  location.replace('/auctions/'+id);
}
</script>

<div class="hero-unit">

<h1>大放出オークション</h1>
<p>
ついに！４年に１度のオリンピックがついに！ついに開幕しました！<br />
五月女商会も社を挙げてサムライたちを応援しています！<br />
<br />
そんなわけで、五月女商会ではオリンピック開催を記念してスペシャル新企画「大放出オークション」を開催いたします！！！！
</p>
</div>

<hr />

<div class="span8">
  <h1>開催中のオークション</h1>
  
  <table class="table table-striped">
  <tbody>
  <% @auctions.each do |auction| %>
  <tr onClick="jump(<%= auction.id %>)">
      <td>
          <img src="<%= auction.image_url_sub %>" width="120px"/>
      </td>
      <td>
          <span class="">★<%= auction.start_at %>開始★</span>
          <br />
          <span class=""><%= auction.title %></span>
      </td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>

sotm/app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

sotm/app/views/auctions/show.html.erb
<script language="javascript">
$(function(){
  updateBiddings();
  $('#button_updateBiddings').click(function(){updateBiddings()});
  $('#button_bidding').click(function(){bidding()});
});
function updateBiddings(){
  $.getJSON('/biddings.json',{},function(jsondata){
    $('#tbody_bidding').children().remove();
    $(jsondata).each(function(i,val){
      if( val['auction_uniq_id'] == '<%= @auction.auction_uniq_id %>' ){
        $('#tbody_bidding').append(
            '<tr>'
          + '<td>'+val['name']+'</td>'
          + '<td>'+val['price']+'</td>'
          + '<td>'+val['created_at']+'</td>'
          + '<tr>'
        );
      }
    });
  });
};
function bidding(){
  if ( $('#bidding_name').val() != '' && $('#bidding_price').val() != ''){
    $.post('/auctions/bid', $('form').serialize(), function(){updateBiddings()});
    $('#bidding_name').val('');
    $('#bidding_price').val('');
  };
};
</script>

<p id="notice"><%= notice %></p>

<h1>
  <%= @auction.title %>
</h1>

<img src="<%= @auction.image_url_main %>" />

<div>
  <%= @auction.start_at %> 開始
</div>

<div>
<blockquote>
  <%= @auction.description %>
</blockquote>
</div>

<div style="float:left">
<%= form_for :bidding, :url => '' do |f| %>
name: <%= f.text_field:name%>
price: <%= f.text_field:price%>
<%= f.hidden_field:auction_uniq_id, :value => @auction.auction_uniq_id %>
<% end %>
</div>
<div style="float:left">
  <button id="button_bidding" class="btn btn-info">BID</button>
</div>
<hr  style="width:100%"/>
<h1>biddings
<button id="button_updateBiddings" class="btn">update</button></h1>
<table class="table table-striped">
<tbody id="tbody_bidding">
</tbody>
</table>

sotm/app/views/biddings/_form.html.erb
<%= form_for(@bidding) do |f| %>
  <% if @bidding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bidding.errors.count, "error") %> prohibited this bidding from being saved:</h2>

      <ul>
      <% @bidding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :auction_uniq_id %><br />
    <%= f.text_field :auction_uniq_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

sotm/app/views/biddings/edit.html.erb
<h1>Editing bidding</h1>

<%= render 'form' %>

<%= link_to 'Show', @bidding %> |
<%= link_to 'Back', biddings_path %>

sotm/app/views/biddings/index.html.erb
<h1>Listing biddings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Auction uniq</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @biddings.each do |bidding| %>
  <tr>
    <td><%= bidding.name %></td>
    <td><%= bidding.price %></td>
    <td><%= bidding.auction_uniq_id %></td>
    <td><%= link_to 'Show', bidding %></td>
    <td><%= link_to 'Edit', edit_bidding_path(bidding) %></td>
    <td><%= link_to 'Destroy', bidding, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bidding', new_bidding_path %>

sotm/app/views/biddings/new.html.erb
<h1>New bidding</h1>

<%= render 'form' %>

<%= link_to 'Back', biddings_path %>

sotm/app/views/biddings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bidding.name %>
</p>

<p>
  <b>Price:</b>
  <%= @bidding.price %>
</p>

<p>
  <b>Auction uniq:</b>
  <%= @bidding.auction_uniq_id %>
</p>


<%= link_to 'Edit', edit_bidding_path(@bidding) %> |
<%= link_to 'Back', biddings_path %>

sotm/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "オリンピック開催記念！大放出オークション - メガネと自転車の五月女商会" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">メガネと自転車の五月女商会</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "About", "/pages/about"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; SAOTOME Company 2012</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

sotm/app/views/pages/about.html.erb
<h1>事業概要</h1>

<ul>
<li>#トラしゅ の度に登場します</li>
<li>実在の会社ではありませんし何も関係はありません</li>
<li>山◯くんはめげないでえらいと思います</li>
<li>ncstudy, odstudy, hbstudy共催です</li>
<li>いつも準備が間に合わない。でも間に合う不思議</li>
<li>苦情は受け付けませんが仰っていただく分には構いません</li>
</ul>

sotm/app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>